[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20"]

[phases.build]
cmds = [
  "npm install -g surge",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
